## Preprocessing the data: minmax scaler


In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [2]:
x_train = pd.read_csv('x_train.csv', dtype=np.float64, header=None)
x_test = pd.read_csv('x_test.csv', dtype=np.float64, header=None)
y_train = pd.read_csv('y_train.csv', dtype=np.float64, header=None)
y_test = pd.read_csv('y_test.csv', dtype=np.float64, header=None)


scaler = MinMaxScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)



In [3]:
import torch
import torch.nn as nn
# Step 3: Convert scaled data to PyTorch tensors
x_train_tensor = torch.tensor(x_train_scaled, dtype=torch.float32)
x_test_tensor = torch.tensor(x_test_scaled, dtype=torch.float32)

# Convert y_train and y_test to tensors (assuming these are labels)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32)
print(y_train_tensor)
input_size = 63
output_size = 27

config = [(32, 'RELU'), (16, 'RELU') , (8, 'RELU')]

import torch
import torch.nn as nn
import torch.nn.functional as F
from coordsnn import CoordsNN


model = CoordsNN(input_size=input_size, config=config, output_size=27)

model.fit(x_train_tensor, y_train_tensor,val_data=[x_test_tensor, y_test_tensor])

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.]])
Epoch 1/100 - Loss: 3.2325 - Accuracy: 0.0695
Epoch 1 - Val Loss: 3.0586 - Val Acc: 0.0855
Epoch 2/100 - Loss: 2.8076 - Accuracy: 0.1054
Epoch 2 - Val Loss: 2.5393 - Val Acc: 0.2087
Epoch 3/100 - Loss: 2.3521 - Accuracy: 0.2503
Epoch 3 - Val Loss: 2.1673 - Val Acc: 0.2756
Epoch 4/100 - Loss: 2.0159 - Accuracy: 0.3533
Epoch 4 - Val Loss: 1.8974 - Val Acc: 0.4328
Epoch 5/100 - Loss: 1.7585 - Accuracy: 0.4455
Epoch 5 - Val Loss: 1.6743 - Val Acc: 0.4843
Epoch 6/100 - Loss: 1.5414 - Accuracy: 0.5143
Epoch 6 - Val Loss: 1.4660 - Val Acc: 0.5162
Epoch 7/100 - Loss: 1.3430 - Accuracy: 0.5750
Epoch 7 - Val Loss: 1.2931 - Val Acc: 0.5750
Epoch 8/100 - Loss: 1.1899 - Accuracy: 0.6292
Epoch 8 - Val Loss: 1.1692 - Val Acc: 0.6347
Epoch 9/100 - Loss

In [4]:
model.evaluate(x_test_tensor, y_test_tensor)   

(0.33878329396247864, 0.9185986604842864)

In [5]:

model.predict(x_test_tensor[0])

tensor([9])

In [6]:
# import pickle
# with open('model.pkl', 'wb') as f:
#     pickle.dump(model, f)
    

In [7]:
# import numpy as np
# import tensorflow as tf
# from sklearn.preprocessing import MinMaxScaler

# # Assuming x_train and y_train are your raw data
# # Scale your data
# scaler = MinMaxScaler()
# x_train_scaled = scaler.fit_transform(x_train)
# x_test_scaled = scaler.transform(x_test)

# # Convert labels to integer format if they're one-hot encoded
# # Uncomment this if you had one-hot encoded labels
# # y_train = np.argmax(y_train, axis=1)
# # y_test = np.argmax(y_test, axis=1)

# # Define the model
# model = tf.keras.models.Sequential([
#     tf.keras.layers.Dense(32, input_shape=(63,), activation='relu'),
#     tf.keras.layers.Dense(16, activation='relu'),
#     tf.keras.layers.Dense(8, activation='relu'),
#     tf.keras.layers.Dense(27, activation='softmax')
# ])

# # Compile the model
# model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# # Train the model
# model.fit(x_train_scaled, y_train, epochs=100, batch_size=32, validation_data=(x_test_scaled, y_test))

# # Evaluate the model
# loss, accuracy = model.evaluate(x_test_scaled, y_test)
# print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

# # Make predictions
# predictions = model.predict(x_test_scaled[0:1])
# predicted_class = np.argmax(predictions, axis=-1)
# print(f'Predicted class: {predicted_class}')


In [8]:
# import pickle
# # Save the model
# with open('modeltf.pkl', 'wb') as f:
#     pickle.dump(model, f)

x = torch.tensor([-0.0586,  0.2634,  0.5198,  0.0955,  0.6333,  0.5440,  0.1848,  0.8022,
          0.6143,  0.3406,  0.8915,  0.6649,  0.5016,  0.9127,  0.7000,  0.4655,
          0.5711,  0.6309,  0.7355,  0.6604,  0.6647,  0.8865,  0.7695,  0.6925,
          0.9829,  0.8751,  0.7066,  0.4031,  0.3251,  0.6898,  0.7941,  0.3866,
          0.7280,  0.9782,  0.4547,  0.7564,  1.0962,  0.5945,  0.7730,  0.2571,
          0.0742,  0.7606,  0.5744,  0.2358,  0.7653,  0.5791,  0.5061,  0.7787,
          0.5588,  0.7376,  0.7827,  0.1611, -0.1317,  0.7067,  0.3598, -0.0694,
          0.7587,  0.3933,  0.1893,  0.7745,  0.4247,  0.4168,  0.7806])

model.predict(x).item()

3

In [9]:
# save model 
# model.save('modeltf.h5')
x_test_tensor[0]

tensor([0.2935, 0.8759, 0.7572, 0.4725, 0.9811, 0.5793, 0.6481, 0.9099, 0.5604,
        0.5928, 0.7559, 0.4060, 0.3691, 0.7045, 0.2037, 0.9198, 0.6101, 0.3540,
        0.7507, 0.5749, 0.0906, 0.6686, 0.7260, 0.1067, 0.5645, 0.6899, 0.3508,
        0.3933, 0.4824, 0.7849, 0.5379, 0.4170, 0.0712, 0.5177, 0.6715, 0.1065,
        0.5480, 0.6919, 0.3287, 0.1652, 0.3001, 0.6875, 0.2629, 0.4029, 0.1959,
        0.2934, 0.6118, 0.1100, 0.3490, 0.7514, 0.3350, 0.1817, 0.3841, 0.6503,
        0.1658, 0.2849, 0.6338, 0.2099, 0.1094, 0.4138, 0.2888, 0.1084, 0.3079])

In [19]:
import cv2
import mediapipe as mp
import numpy as np

class HandDetector:
    def __init__(self, static_image_mode=False, max_hands=2, min_detection_confidence=0.5, min_tracking_confidence=0.5):
        # Initialize MediaPipe Hands
        self.static_image_mode = static_image_mode
        self.max_hands = max_hands
        self.min_detection_confidence = min_detection_confidence
        self.min_tracking_confidence = min_tracking_confidence
        
        self.mp_hands = mp.solutions.hands
        self.hands = self.mp_hands.Hands(
            static_image_mode=self.static_image_mode,
            max_num_hands=self.max_hands,
            min_detection_confidence=self.min_detection_confidence,
            min_tracking_confidence=self.min_tracking_confidence
        )
        self.mp_drawing = mp.solutions.drawing_utils

    def normalize_landmarks(self, hand_landmarks, image_width, image_height):
        """ Normalize hand landmarks within the hand's bounding box and center them. """
        x_coords = [landmark.x * image_width for landmark in hand_landmarks.landmark]
        y_coords = [landmark.y * image_height for landmark in hand_landmarks.landmark]

        # Calculate bounding box
        x_min, x_max = min(x_coords), max(x_coords)
        y_min, y_max = min(y_coords), max(y_coords)
        
        # Bounding box dimensions
        box_width = x_max - x_min
        box_height = y_max - y_min

        # Normalize and center landmarks within the bounding box
        normalized_landmarks = []
        for landmark in hand_landmarks.landmark:
            # Normalizing x and y coordinates to be between 0 and 1 within the bounding box
            x = (landmark.x * image_width - x_min) / box_width - 0.5
            y = (landmark.y * image_height - y_min) / box_height - 0.5
            z = landmark.z  # Z can be kept as is, or normalized if needed
            normalized_landmarks.extend([x, y, z])

        return np.array(normalized_landmarks), (x_min, y_min, x_max, y_max)

    def detect_hands(self):
        # Open a connection to the webcam
        cap = cv2.VideoCapture(0)

        while cap.isOpened():
            success, image = cap.read()
            if not success:
                print("Ignoring empty camera frame.")
                continue
            
            # Flip the image horizontally for a later selfie-view display
            image = cv2.flip(image, 1)
            image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            image_height, image_width, _ = image.shape

            # Process the image and find hands
            results = self.hands.process(image_rgb)

            # Draw hand landmarks on the image and normalize landmarks
            if results.multi_hand_landmarks:
                for hand_landmarks in results.multi_hand_landmarks:
                    self.mp_drawing.draw_landmarks(image, hand_landmarks, self.mp_hands.HAND_CONNECTIONS)
                    normalized_landmarks, bbox = self.normalize_landmarks(hand_landmarks, image_width, image_height)
                    x_min, y_min, x_max, y_max = bbox
                    cv2.rectangle(image, (int(x_min), int(y_min)), (int(x_max), int(y_max)), (0, 255, 0), 2)

                    normalized_landmarks = np.array(normalized_landmarks).reshape(63, 1).T
                    # Scale the normalized landmarks
                    scaled = scaler.transform(normalized_landmarks)
                    tensor_data = torch.tensor(scaled, dtype=torch.float32)
                    prediction = model.predict(tensor_data[0])
                    
                    label = ['SPACE','A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
                    if prediction is not [0]*27:
                        # show the letter
                        
                        cv2.putText(image, label[prediction.item()], (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 255, 0), 2, cv2.LINE_AA)

                      # Print the normalized landmarks
                    # print(model.predict(tensor_data))

            # Display the resulting frame
            cv2.imshow('Hand Detection', image)

            # Break the loop when 'q' is pressed
            if cv2.waitKey(5) & 0xFF == ord('q'):
                break

        cap.release()
        cv2.destroyAllWindows()

if __name__ == "__main__":
    detector = HandDetector()
    detector.detect_hands()


c:\Users\Aship\anaconda3\envs\ufcpytorch\Lib\site-packages\google\protobuf\symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '
c:\Users\Aship\anaconda3\envs\ufcpytorch\Lib\site-packages\google\protobuf\symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '
c:\Users\Aship\anaconda3\envs\ufcpytorch\Lib\site-packages\google\protobuf\symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '
c

In [11]:

x_train_tensor[0], y_train_tensor[0]
plt.imshow(x_train_tensor[0].reshape(21, 3))

NameError: name 'plt' is not defined